TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE user_entity CASCADE;
TRUNCATE TABLE question CASCADE;
TRUNCATE TABLE answer CASCADE;
TRUNCATE TABLE reputation CASCADE;
TRUNCATE TABLE votes_on_answers CASCADE;