TRUNCATE TABLE chat CASCADE;
TRUNCATE TABLE role CASCADE;
TRUNCATE TABLE user_entity CASCADE;
TRUNCATE TABLE group_chat CASCADE;
TRUNCATE TABLE user_chat_pin CASCADE;
TRUNCATE TABLE groupchat_has_users CASCADE;